"""Add FailedOperation table for retry logic

Revision ID: 06f6b9ab1091
Revises: 6450b6a24d0c
Create Date: 2025-09-16 16:06:20.255190

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06f6b9ab1091'
down_revision: str | Sequence[str] | None = '6450b6a24d0c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(), nullable=False),
    sa.Column('operation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_failed_operations'))
    )
    op.create_index('ix_failed_operations_failed_at', 'failed_operations', ['failed_at'], unique=False)
    op.create_index('ix_failed_operations_next_retry_at', 'failed_operations', ['next_retry_at'], unique=False)
    op.create_index('ix_failed_operations_operation_type', 'failed_operations', ['operation_type'], unique=False)
    op.create_index('ix_failed_operations_retry_count', 'failed_operations', ['retry_count'], unique=False)
    op.create_index('ix_failed_operations_status', 'failed_operations', ['status'], unique=False)
    op.create_index('ix_failed_operations_status_next_retry', 'failed_operations', ['status', 'next_retry_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_failed_operations_status_next_retry', table_name='failed_operations')
    op.drop_index('ix_failed_operations_status', table_name='failed_operations')
    op.drop_index('ix_failed_operations_retry_count', table_name='failed_operations')
    op.drop_index('ix_failed_operations_operation_type', table_name='failed_operations')
    op.drop_index('ix_failed_operations_next_retry_at', table_name='failed_operations')
    op.drop_index('ix_failed_operations_failed_at', table_name='failed_operations')
    op.drop_table('failed_operations')
    # ### end Alembic commands ###
