"""Add RoleAction table for role-action relationships

Revision ID: 6450b6a24d0c
Revises: 9fb1ac999ec3
Create Date: 2025-09-16 16:03:32.964689

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6450b6a24d0c'
down_revision: str | Sequence[str] | None = '9fb1ac999ec3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_actions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], name=op.f('fk_role_actions_action_id_actions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_role_actions_granted_by_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_actions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'action_id', name=op.f('pk_role_actions'))
    )
    op.create_index('ix_role_actions_action_id', 'role_actions', ['action_id'], unique=False)
    op.create_index('ix_role_actions_granted_at', 'role_actions', ['granted_at'], unique=False)
    op.create_index('ix_role_actions_granted_by', 'role_actions', ['granted_by'], unique=False)
    op.create_index('ix_role_actions_role_action', 'role_actions', ['role_id', 'action_id'], unique=False)
    op.create_index('ix_role_actions_role_id', 'role_actions', ['role_id'], unique=False)
    op.create_index('ix_actions_name', 'actions', ['name'], unique=False)
    op.create_index('ix_admin_audit_actor_operation', 'admin_audit', ['actor_subject', 'operation'], unique=False)
    op.create_index('ix_admin_audit_actor_subject', 'admin_audit', ['actor_subject'], unique=False)
    op.create_index('ix_admin_audit_actor_user_id', 'admin_audit', ['actor_user_id'], unique=False)
    op.create_index('ix_admin_audit_operation', 'admin_audit', ['operation'], unique=False)
    op.create_index('ix_admin_audit_operation_timestamp', 'admin_audit', ['operation', 'timestamp'], unique=False)
    op.create_index('ix_admin_audit_success', 'admin_audit', ['success'], unique=False)
    op.create_index('ix_admin_audit_target_type', 'admin_audit', ['target_type'], unique=False)
    op.create_index('ix_admin_audit_target_type_timestamp', 'admin_audit', ['target_type', 'timestamp'], unique=False)
    op.create_index('ix_admin_audit_timestamp', 'admin_audit', ['timestamp'], unique=False)
    op.create_index('ix_endpoints_action_id', 'endpoints', ['action_id'], unique=False)
    op.create_index('ix_endpoints_created_at', 'endpoints', ['created_at'], unique=False)
    op.create_index('ix_endpoints_created_by', 'endpoints', ['created_by'], unique=False)
    op.create_index('ix_endpoints_method', 'endpoints', ['method'], unique=False)
    op.create_index('ix_endpoints_method_path', 'endpoints', ['method', 'path_pattern'], unique=False)
    op.create_index('ix_endpoints_path_pattern', 'endpoints', ['path_pattern'], unique=False)
    op.create_index('ix_endpoints_updated_at', 'endpoints', ['updated_at'], unique=False)
    op.create_index('ix_group_mgmt_rights_created_at', 'group_management_rights', ['created_at'], unique=False)
    op.create_index('ix_group_mgmt_rights_created_by', 'group_management_rights', ['created_by'], unique=False)
    op.create_index('ix_group_mgmt_rights_manager_group_id', 'group_management_rights', ['manager_group_id'], unique=False)
    op.create_index('ix_group_mgmt_rights_target_pattern', 'group_management_rights', ['target_group_pattern'], unique=False)
    op.create_index('ix_group_roles_group_id', 'group_roles', ['group_id'], unique=False)
    op.create_index('ix_group_roles_group_role', 'group_roles', ['group_id', 'role_id'], unique=False)
    op.create_index('ix_group_roles_role_id', 'group_roles', ['role_id'], unique=False)
    op.create_index('ix_groups_created_at', 'groups', ['created_at'], unique=False)
    op.create_index('ix_groups_created_by', 'groups', ['created_by'], unique=False)
    op.create_index('ix_groups_name', 'groups', ['name'], unique=False)
    op.create_index('ix_groups_name_prefix', 'groups', ['name'], unique=False, postgresql_ops={'name': 'varchar_pattern_ops'})
    op.create_index('ix_memberships_granted_at', 'memberships', ['granted_at'], unique=False)
    op.create_index('ix_memberships_granted_by', 'memberships', ['granted_by'], unique=False)
    op.create_index('ix_memberships_group_id', 'memberships', ['group_id'], unique=False)
    op.create_index('ix_memberships_group_user', 'memberships', ['group_id', 'user_id'], unique=False)
    op.create_index('ix_memberships_user_id', 'memberships', ['user_id'], unique=False)
    op.create_index('ix_roles_name', 'roles', ['name'], unique=False)
    op.create_index('ix_user_roles_granted_at', 'user_roles', ['granted_at'], unique=False)
    op.create_index('ix_user_roles_granted_by', 'user_roles', ['granted_by'], unique=False)
    op.create_index('ix_user_roles_role_id', 'user_roles', ['role_id'], unique=False)
    op.create_index('ix_user_roles_user_id', 'user_roles', ['user_id'], unique=False)
    op.create_index('ix_user_roles_user_role', 'user_roles', ['user_id', 'role_id'], unique=False)
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_display_name', 'users', ['display_name'], unique=False)
    op.create_index('ix_users_subject', 'users', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_subject', table_name='users')
    op.drop_index('ix_users_display_name', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_index('ix_user_roles_user_role', table_name='user_roles')
    op.drop_index('ix_user_roles_user_id', table_name='user_roles')
    op.drop_index('ix_user_roles_role_id', table_name='user_roles')
    op.drop_index('ix_user_roles_granted_by', table_name='user_roles')
    op.drop_index('ix_user_roles_granted_at', table_name='user_roles')
    op.drop_index('ix_roles_name', table_name='roles')
    op.drop_index('ix_memberships_user_id', table_name='memberships')
    op.drop_index('ix_memberships_group_user', table_name='memberships')
    op.drop_index('ix_memberships_group_id', table_name='memberships')
    op.drop_index('ix_memberships_granted_by', table_name='memberships')
    op.drop_index('ix_memberships_granted_at', table_name='memberships')
    op.drop_index('ix_groups_name_prefix', table_name='groups', postgresql_ops={'name': 'varchar_pattern_ops'})
    op.drop_index('ix_groups_name', table_name='groups')
    op.drop_index('ix_groups_created_by', table_name='groups')
    op.drop_index('ix_groups_created_at', table_name='groups')
    op.drop_index('ix_group_roles_role_id', table_name='group_roles')
    op.drop_index('ix_group_roles_group_role', table_name='group_roles')
    op.drop_index('ix_group_roles_group_id', table_name='group_roles')
    op.drop_index('ix_group_mgmt_rights_target_pattern', table_name='group_management_rights')
    op.drop_index('ix_group_mgmt_rights_manager_group_id', table_name='group_management_rights')
    op.drop_index('ix_group_mgmt_rights_created_by', table_name='group_management_rights')
    op.drop_index('ix_group_mgmt_rights_created_at', table_name='group_management_rights')
    op.drop_index('ix_endpoints_updated_at', table_name='endpoints')
    op.drop_index('ix_endpoints_path_pattern', table_name='endpoints')
    op.drop_index('ix_endpoints_method_path', table_name='endpoints')
    op.drop_index('ix_endpoints_method', table_name='endpoints')
    op.drop_index('ix_endpoints_created_by', table_name='endpoints')
    op.drop_index('ix_endpoints_created_at', table_name='endpoints')
    op.drop_index('ix_endpoints_action_id', table_name='endpoints')
    op.drop_index('ix_admin_audit_timestamp', table_name='admin_audit')
    op.drop_index('ix_admin_audit_target_type_timestamp', table_name='admin_audit')
    op.drop_index('ix_admin_audit_target_type', table_name='admin_audit')
    op.drop_index('ix_admin_audit_success', table_name='admin_audit')
    op.drop_index('ix_admin_audit_operation_timestamp', table_name='admin_audit')
    op.drop_index('ix_admin_audit_operation', table_name='admin_audit')
    op.drop_index('ix_admin_audit_actor_user_id', table_name='admin_audit')
    op.drop_index('ix_admin_audit_actor_subject', table_name='admin_audit')
    op.drop_index('ix_admin_audit_actor_operation', table_name='admin_audit')
    op.drop_index('ix_actions_name', table_name='actions')
    op.drop_index('ix_role_actions_role_id', table_name='role_actions')
    op.drop_index('ix_role_actions_role_action', table_name='role_actions')
    op.drop_index('ix_role_actions_granted_by', table_name='role_actions')
    op.drop_index('ix_role_actions_granted_at', table_name='role_actions')
    op.drop_index('ix_role_actions_action_id', table_name='role_actions')
    op.drop_table('role_actions')
    # ### end Alembic commands ###
